### PR TITLE
Update README to reflect renaming meta to working group

### PR DESCRIPTION
**Pull request by dcodeIO**
An attempt to concretize and slim down the README a bit, according to the latest rename and split into a WG and CG.

cc @torch2424

### CODE REVIEW

**Comment by dcodeIO** [comment]
Converting this to draft, in favor of https://github.com/AssemblyScript/working-group/pull/34 😅

**Comment by torch2424** [comment]
cc @dcodeIO @MaxGraey @willemneal @nearmax Okay now this is ready and the one we can review haha! :joy:

**Comment by dcodeIO** [comment]
Gave it one more read. If it still looks good to you, feel free to merge :)

**Comment by torch2424** [comment]
@dcodeIO Awesome! :smile: :+1: Merginig!

**Comment by nearmax** [comment]
@dcodeIO Thank you!

**Pull request merged**
